use_frameworks!

platform :ios, '9.0'

target 'GhostPlusSwift_Example' do
  
  pod 'Alamofire', '~> 4'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'ObjectMapper', '~> 4'
  pod 'SwiftyXMLParser', '~> 5'
  pod 'KeychainSwift', '~> 19'
  pod 'CryptoSwift', '~> 1'
  pod 'Device', '~> 3'
  
  pod 'GhostPlusSwift', :path => '../'

end
